export type EndpointModules = "InstrumentsService" | "MarketDataService";

export const apiEndpoints: Record<EndpointModules, Record<string, string>> = {
    InstrumentsService: {
        Bonds: "Bonds",
        BondBy: "BondBy",
        Currencies: "Currencies",
        CurrencyBy: "CurrencyBy",
        EditFavorites: "EditFavorites",
        Etfs: "Etfs",
        EtfBy: "EtfsBy",
        FindInstrument: "FindInstrument",
        Futures: "Futures",
        FutureBy: "FuturesBy",
        GetAccruedInterests: "GetAccruedInterests",
        GetAssets: "GetAssets",
        GetAssetBy: "GetAssetBy",
        GetAssetFundamentals: "GetAssetFundamentals",
        GetAssetReports: "GetAssetReports",
        GetBondCoupons: "GetBondCoupons",
        GetBondEvents: "GetBondEvents",
        GetBrandBy: "GetBrandBy",
        GetBrands: "GetBrands",
        GetConsensusForecasts: "GetConsensusForecasts",
        GetCountries: "GetCountries",
        GetDividends: "GetDividends",
        GetFavorites: "GetFavorites",
        GetForecastBy: "GetForecastBy",
        GetFuturesMargin: "GetFuturesMargin",
        GetInstrumentBy: "GetInstrumentBy",
        Indicatives: "Indicatives",
        OptionBy: "OptionBy",
        Options: "Options",
        OptionsBy: "OptionsBy",
        ShareBy: "ShareBy",
        Shares: "Shares",
        TradingSchedules: "TradingSchedules",
    },
    MarketDataService: {
        OrderBook: "GetOrderBook",
        Trades: "GetTrades",
    },
};

export default apiEndpoints;
